########################################
#    Thanks to @countrysideboy, @ptbsare
########################################
sensor:
  - platform: xiaomi_miot_raw
    name: air_monitor
    host: 10.0.0.42
    token: xxxxxxx
    mapping:
      humidity:
        siid: 3
        piid: 1
      pm2_5:
        siid: 3
        piid: 4
      pm10:
        siid: 3
        piid: 5
      temperature:
        siid: 3
        piid: 7
      co2:
        siid: 3
        piid: 8
      battery:
        siid: 4
        piid: 1
      charging:
        siid: 4
        piid: 2
      voltage:
        siid: 4
        piid: 3
    params:
    sensor_property: co2
    sensor_unit: 'ppm'
    scan_interval: 3
